### ISSUE TITLE
A contribution guideline is needed

### ISSUE THREAD

**Issue by diegoperini** [sangupta/ps#1]
Title is quite descriptive but I'd like to add one more thing. Which language will be the base for the solutions? Is there such limit?

**Comment by sangupta** [comment]
Thanks for the suggestions. I will be adding contribution guidelines very shortly.

There is no such preferred language per se, but being a Java-developer I would prefer that. For all other contributions we would need to rely on the community for code reviews.

Again, the idea is to bring out concepts and pointers towards implementation, than providing the implementation directly.

**Comment by sangupta** [comment]
Closing this issue - as I just added the contribution guidelines.
